baseURL = 'https://j-faria.github.io/space/'
locale = 'en-us'
title = 'João Faria'

theme = 'celadon'


[params]
  description = 'Astronomer searching for exoplanets'
  email = 'joao.faria@unige.ch'
  location = 'Geneva, Switzerland'

[params.homepage]
  sections = ["hero", "latest", "software", "writing"]

  [params.homepage.hero]
    enable = true
    layout = "hero"
    title = "About"

  [params.homepage.latest]
    enable = true
    layout = "news"
    title = "Latest Research"

  [params.homepage.software]
    enable = true
    layout = "cards"
    title = "Software"
    limit = 6

  [params.homepage.writing]
    enable = false
    layout = "grid"
    title = "Writing"

